defaults: &defaults
  working_directory: /home/circleci/kotlin-spring-boot-reactjs-poc
  docker:
    - image: circleci/openjdk:8-jdk-browsers
    
version: 2
jobs:
  build:
    <<: *defaults
    steps:

      - checkout

      - restore_cache:
          key: kotlin-spring-boot-reactjs-poc-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: kotlin-spring-boot-reactjs-poc-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/*.jar
          
      - persist_to_workspace:
          root: target/
          paths:
            - .
 
  downstream:
    <<: *defaults
    steps:
      - attach_workspace:
          at: workspace/
          
      - run: ls -la workspace/

workflows:
  version: 2

  btd:
    jobs:
      - build
      - downstream:
          requires:
            - build

